# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('print_name', models.TextField()),
                ('group_acc', models.CharField(max_length=15)),
                ('op_bal', models.IntegerField()),
                ('dr_cr', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('address1', models.TextField()),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('contact_per', models.CharField(max_length=20)),
                ('birthday_on', models.DateField()),
                ('anniv_on', models.DateField()),
                ('bank_name', models.TextField()),
                ('bank_acc_no', models.CharField(max_length=20)),
                ('cheque_p_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_group_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='BillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_head', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.IntegerField()),
                ('d_c', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.IntegerField()),
                ('d_c', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.IntegerField()),
                ('d_c', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.IntegerField()),
                ('d_c', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vch_no', models.IntegerField()),
                ('d_c', models.IntegerField()),
                ('account_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vch_no', models.IntegerField()),
                ('d_c', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('short_narration', models.TextField()),
            ],
        ),
    ]
