# Generated by Django 6.0.2 on 2026-02-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='anniv_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
