# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caste_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('prefix', models.CharField(blank=True, max_length=5)),
                ('start_from', models.DateField()),
                ('incharge', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gatepass/')),
                ('profession', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('purpose', models.TextField()),
                ('date_of_visit', models.DateField()),
                ('time_of_visit', models.DateTimeField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('expected_return_time', models.DateTimeField()),
                ('proof_of_identity', models.TextField()),
                ('items_retained', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=20)),
                ('student_middle_name', models.CharField(blank=True, max_length=20)),
                ('student_last_name', models.CharField(blank=True, max_length=20)),
                ('student_class', models.CharField(max_length=10)),
                ('student_section', models.CharField(max_length=5)),
                ('student_roll_no', models.IntegerField()),
                ('route', models.CharField(blank=True, max_length=20, null=True)),
                ('caste', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('house', models.CharField(max_length=10)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('admission_no', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('student_dob', models.DateField()),
                ('house_no', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=50)),
                ('other_info', models.CharField(blank=True, max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('fathers_first_name', models.CharField(max_length=20)),
                ('fathers_middle_name', models.CharField(blank=True, max_length=20)),
                ('fathers_last_name', models.CharField(blank=True, max_length=25)),
                ('f_mobile', models.CharField(max_length=15)),
                ('f_qual', models.CharField(blank=True, max_length=15)),
                ('f_occu', models.CharField(blank=True, max_length=15)),
                ('f_dob', models.DateField(blank=True, null=True)),
                ('f_photo', models.ImageField(blank=True, null=True, upload_to='fathers/')),
                ('mothers_first_name', models.CharField(max_length=20)),
                ('mothers_middle_name', models.CharField(blank=True, max_length=15)),
                ('mothers_last_name', models.CharField(blank=True, max_length=20)),
                ('m_mobile', models.CharField(max_length=15)),
                ('m_qual', models.CharField(blank=True, max_length=15)),
                ('m_occu', models.CharField(blank=True, max_length=15)),
                ('m_dob', models.DateField(blank=True, null=True)),
                ('m_photo', models.ImageField(blank=True, null=True, upload_to='mothers/')),
                ('parents_wedding_date', models.DateField(blank=True, null=True)),
                ('las', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=30)),
                ('last_exam_given', models.CharField(blank=True, max_length=20)),
                ('year', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('board', models.CharField(blank=True, max_length=10)),
                ('bg', models.CharField(blank=True, max_length=5)),
                ('vl', models.IntegerField(default=0)),
                ('vr', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('dental_hy', models.CharField(blank=True, max_length=20)),
                ('tc', models.BooleanField(default=False)),
                ('cc', models.BooleanField(default=False)),
                ('report_cc', models.BooleanField(default=False)),
                ('dob_certificate', models.BooleanField(default=False)),
                ('admission_form_no', models.IntegerField()),
                ('date_admission', models.DateField()),
                ('ledger_balance', models.IntegerField(default=0)),
                ('fees_balance', models.IntegerField(default=0)),
                ('comments', models.CharField(blank=True, max_length=50)),
                ('hostel_room_no', models.CharField(blank=True, max_length=5)),
                ('bed_no', models.IntegerField(default=0)),
                ('scholarship_no', models.IntegerField(default=0)),
                ('aadhar_uid', models.CharField(blank=True, max_length=20)),
                ('family', models.CharField(blank=True, max_length=20)),
                ('status_adm', models.CharField(blank=True, max_length=10)),
                ('discontinue_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeavingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
    ]
