# Generated by Django 6.0.2 on 2026-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.IntegerField(),
        ),
    ]
