# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('class_name', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('student_id', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
