# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=100, unique=True)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=15)),
                ('fax_no', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField()),
                ('website', models.URLField(blank=True, max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('pan_no', models.CharField(blank=True, max_length=15)),
                ('affiliation', models.TextField(blank=True)),
                ('license_no', models.CharField(blank=True, max_length=20)),
                ('service_tax_no', models.CharField(blank=True, max_length=20)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('dise_code', models.IntegerField(blank=True, null=True)),
                ('school_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=50, unique=True)),
                ('owner_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.TextField()),
                ('freq', models.CharField(max_length=20)),
                ('january', models.IntegerField(blank=True, null=True)),
                ('february', models.IntegerField(blank=True, null=True)),
                ('march', models.IntegerField(blank=True, null=True)),
                ('april', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('june', models.IntegerField(blank=True, null=True)),
                ('july', models.IntegerField(blank=True, null=True)),
                ('august', models.IntegerField(blank=True, null=True)),
                ('september', models.IntegerField(blank=True, null=True)),
                ('october', models.IntegerField(blank=True, null=True)),
                ('november', models.IntegerField(blank=True, null=True)),
                ('december', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_text', models.TextField()),
            ],
        ),
    ]
