# Generated by Django 6.0.2 on 2026-02-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=15)),
                ('fax_no', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField()),
                ('website', models.URLField(blank=True, max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('pan_no', models.CharField(blank=True, max_length=15)),
                ('affiliation', models.TextField(blank=True)),
                ('license_no', models.CharField(blank=True, max_length=20)),
                ('service_tax_no', models.CharField(blank=True, max_length=20)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
                ('dise_code', models.IntegerField(blank=True, null=True)),
                ('school_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='dise_code',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='fax_no',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='license_no',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='school_code',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='service_tax_no',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='session_start',
        ),
        migrations.RemoveField(
            model_name='organisationinfo',
            name='website',
        ),
    ]
