# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_heading', models.TextField()),
                ('group_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=20)),
                ('january', models.IntegerField(blank=True, null=True)),
                ('february', models.IntegerField(blank=True, null=True)),
                ('march', models.IntegerField(blank=True, null=True)),
                ('april', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('june', models.IntegerField(blank=True, null=True)),
                ('july', models.IntegerField(blank=True, null=True)),
                ('august', models.IntegerField(blank=True, null=True)),
                ('september', models.IntegerField(blank=True, null=True)),
                ('october', models.IntegerField(blank=True, null=True)),
                ('november', models.IntegerField(blank=True, null=True)),
                ('december', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeesHeadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_head_group_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FeesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeesPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('receipt_no', models.IntegerField()),
                ('admission_no', models.IntegerField()),
                ('jan', models.IntegerField(default=0)),
                ('feb', models.IntegerField(default=0)),
                ('mar', models.IntegerField(default=0)),
                ('apr', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('jun', models.IntegerField(default=0)),
                ('jul', models.IntegerField(default=0)),
                ('aug', models.IntegerField(default=0)),
                ('sep', models.IntegerField(default=0)),
                ('oct', models.IntegerField(default=0)),
                ('nov', models.IntegerField(default=0)),
                ('dece', models.IntegerField(default=0)),
            ],
        ),
    ]
